export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';
export const EDIT_PRODUCT_LOADING = 'EDIT_PRODUCT_LOADING';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';

export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_PRODUCT_LOADING = 'FETCH_PRODUCT_LOADING';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';